
["Client Setting"]
	#是否固定手电筒光的位置。
	enableFixedFlashlight = false
	#是否启用其它玩家光束可见。
	enablePlayerRay = true
	#是否启用真实照明。
	enableRealLight = true
	#手电筒光强度。
	#Range: 0.0 ~ 1.0
	lightIntensity = 1.0E-5
	#启用光照遮挡，性能敏感，复杂地形慎用
	enableLightOcclusion = false
	#启用圆锥渲染的射线检测（截断）。
	enableConeRaycast = false

