#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jul 18 23:31:19 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Insanity-Shader-Universal-v1.650.zip
enableShaders=true
