#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Sep 05 20:51:47 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Insanity-Shader-Universal-v1.650.zip
enableShaders=false
