#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 30 22:41:39 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=MakeUp-UltraFast-9.5f.zip
